Prune stale branches when fetching from remote
Fixes occasional error where local refs conflict with changes on the
remote:

    error: some local refs could not be updated; try running
    'git remote prune origin' to remove any old, conflicting branches